// components/Button.tsx
import type { JSX } from "solid-js";
import s from "../styles/Button.module.css";

export function Button(
  p: JSX.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "outlined" }
) {
  return (
    <button
      class={s.button}
      classList={{ [s.outlined]: p.variant === "outlined" }}
      {...p}
    />
  );
}

// components/elements/Button.tsx
import classNames from "classnames";
import { ButtonHTMLAttributes, DetailedHTMLProps } from "react";
import styles from "./Button.module.css";

const Button = ({
  isLoading = false,
  ...props
}: DetailedHTMLProps<
  ButtonHTMLAttributes<HTMLButtonElement>,
  HTMLButtonElement
> & {
  isLoading?: boolean;
}) => {
  return (
    <button
      {...props}
      className={classNames(props.className, styles.button, {
        [styles.disabled]: isLoading,
      })}
      disabled={props.disabled || isLoading}
    />
  );
};

export default Button;
