// app/components/Layout/index.tsx
import { useState } from "react";
import { navItems } from "../../utils";
import { HamburgerButton } from "./HamburgerButton";
import { MobileNav } from "./MobileNav";
import { SearchInput } from "./SearchInput";
import { UserItem } from "./UserItem";
import { Link } from "remix";

export function Layout({ children }: { children: React.ReactElement }) {
  const [menuExpanded, setMenuExpanded] = useState(false);

  return (
    <>
      <header className="layout__header">
        <div className="layout__header__logo-container">
          <Link to="/">
            <img className="layout__logo" src="/img/layout/logo.webp" />
          </Link>
        </div>
        <div className="layout__header__search-container">
          <SearchInput />
        </div>
        <div className="layout__header__right-container">
          <UserItem />
          <HamburgerButton
            expanded={menuExpanded}
            onClick={() => setMenuExpanded((e) => !e)}
          />
        </div>
      </header>
      <MobileNav
        expanded={menuExpanded}
        closeMenu={() => setMenuExpanded(false)}
      />
      <nav className="layout__nav">
        <div className="layout__nav__items">
          {navItems.map((navGroup) => (
            <div key={navGroup.title} className="layout__nav__items__column">
              <div className="layout__nav__column__title">{navGroup.title}</div>
              {navGroup.items.map((navItem) => (
                <Link
                  key={navItem}
                  className="layout__nav__link"
                  to={navItem}
                  data-cy={`nav-link-${navItem}`}
                >
                  <img
                    src={`/img/layout/${navItem.replace(" ", "")}.webp`}
                    className="layout__nav__link__icon"
                  />
                  {navItem}
                </Link>
              ))}
            </div>
          ))}
        </div>
      </nav>
      <main className="layout__main">{children}</main>
    </>
  );
}

// scenes/layout/components/Layout.tsx
import { Link } from "solid-app-router";
import { createSignal, For, JSXElement } from "solid-js";
import s from "../styles/Layout.module.css";
import { navItems } from "../utils";
import { HamburgerButton } from "./HamburgerButton";
import { MobileNav } from "./MobileNav";
import { SearchInput } from "./SearchInput";
import { UserItem } from "./UserItem";

export function Layout(p: { children: JSXElement }) {
  const [menuExpanded, setMenuExpanded] = createSignal(false);

  function toggleMenu() {
    setMenuExpanded((expanded) => !expanded);
  }

  return (
    <>
      <header class={s.header}>
        <Link href="/">
          <div class={s.logoContainer}>
            <img class={s.logo} src="/img/layout/logo.webp" />
          </div>
        </Link>
        <div class={s.searchContainer}>
          <SearchInput />
        </div>
        <div class={s.rightContainer}>
          <UserItem />
          <HamburgerButton isExpanded={menuExpanded()} onClick={toggleMenu} />
        </div>
      </header>
      <MobileNav isExpanded={menuExpanded()} />
      <nav class={s.nav}>
        <div class={s.navItems}>
          <For each={navItems}>
            {(navGroup) => (
              <div class={s.navItemColumn}>
                <div class={s.navGroupTitle}>{navGroup.title}</div>
                <For each={navGroup.items}>
                  {(navItem) => (
                    <Link class={s.navLink} href="/">
                      <img
                        src={`/img/layout/${navItem.replace(" ", "")}.webp`}
                        class={s.navIcon}
                      />
                      {navItem}
                    </Link>
                  )}
                </For>
              </div>
            )}
          </For>
        </div>
      </nav>
      <main class={s.main}>{p.children}</main>
    </>
  );
}
